### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by gastonfartek** [aweary/enzyme-adapter-preact#24]
I am getting a `TypeError: Cannot read property 'hasOwnProperty' of undefined`  
at 
```javascript
import { Adapter } from "enzyme-adapter-preact"
```

`node_modules/enzyme-adapter-preact/node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:276:27
      at Object.<anonymous> (node_modules/enzyme-adapter-preact/node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:943:5)
      at Object.<anonymous> (node_modules/enzyme-adapter-preact/node_modules/react-test-renderer/shallow.js:6:20)
      at Object.<anonymous> (node_modules/enzyme-adapter-preact/lib/PreactAdapter.js:20:16)
      at Object.<anonymous> (node_modules/enzyme-adapter-preact/lib/index.js:7:22)`

**Comment by gastonfartek** [comment]
I noticed that `node_modules/enzyme-adapter-preact/lib/PreactAdapter.js:20:16` was requiring `react-test-renderer/shallow`, so I added this to my `jest.config` and it seems to have fixed the issue: 

```javascript 
 moduleNameMapper: {
  //...
  "^react-test-renderer/shallow$": "preact-test-utils"`
}
```

However, are there any downsides about that approach?

**Comment by ijones922** [comment]
Getting the same issue,
```
TypeError: Cannot read property 'hasOwnProperty' of undefined

      1 | const configure = require('enzyme').configure;
    > 2 | const Adapter = require('enzyme-adapter-preact');
        |               ^
      3 |
      4 | configure({ adapter: new Adapter() });
      5 |

      at node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:276:27
      at Object.<anonymous> (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:943:5)
      at Object.<anonymous> (node_modules/react-test-renderer/shallow.js:6:20)
      at Object.<anonymous> (node_modules/enzyme-adapter-preact/lib/PreactAdapter.js:20:16)
      at Object.<anonymous> (node_modules/enzyme-adapter-preact/lib/index.js:7:22)
      at Object.<anonymous> (jest.setup.js:2:15)
```

I added this to my jest.config, but does not resolve the issue:

```
moduleNameMapper: {
		"react-dom/server": "preact-render-to-string",
		"react-dom/test-utils": "preact-test-utils",
		"react-dom": "preact-compat-enzyme",
		"^react-test-renderer/shallow$": "preact-test-utils"
		"react-test-renderer": "preact-test-utils",
		"react-addons-test-utils": "preact-test-utils",
		"react-addons-transition-group": "preact-transition-group",
		"react": "preact-compat-enzyme"
	}
```
